config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "gossips#index"
  resources :gossips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def create()
    #instance de la class Gossips
    @gossip = Gossip.new(gossip_params)
    @gossip.save
    redirect_to @gossip
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy

    redirect_to gossips_path
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def new()
    #instance de la class Gossips
    @gossip = Gossip.new

  end

  def index()
    @gossips = Gossip.all
  end

  def show()
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])

    if @gossip.update(gossip_params)
      redirect_to @gossip
    else
      render 'edit'
    end
  end

  private
  def gossip_params
    params.require(:gossip).permit(:anonimous_autor, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<h1>Edit Gossip</h1>

<%= form_with(model: @gossip) do |form| %>

  <% if @gossip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@gossip.errors.count, "error") %> prohibited
        this gossip from being saved:
      </h2>
      <ul>
        <% @gossip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :anonimous_autor %><br>
    <%= form.text_field :anonimous_autor %>
  </p>

  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', gossips_path %>

app/views/gossips/index.html.erb
<h1>Listing gossips</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Gossip</th>
  </tr>

  <% @gossips.each do |gossip| %>
    <tr>
      <td><%= gossip.anonimous_autor %></td>
      <td><%= gossip.content %></td>
      <td><%= link_to 'Show', gossip_path(gossip) %></td>
      <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
      <td><%= link_to 'Destroy', gossip_path(gossip),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Create New Gossip', new_gossip_path(@gossip) %>

app/views/gossips/new.html.erb
<h1>Post a Gossip</h1>
<%= form_for @gossip do |f| %>
  <h3>Author</h3><%= f.text_field :anonimous_autor %>
  <h3>My Gossip</h3><%= f.text_area :content, size: "60x12" %>
  <%= f.submit "Create" %>
<% end %>

app/views/gossips/show.html.erb
<h1>My Gossip</h1>

<h2>Auteur: <%= @gossip.anonimous_autor %> </h2>
<h2>Content: <%= @gossip.content %> </h2>
<h2>
<%= link_to 'Edit', edit_gossip_path(@gossip) %> |
<%= link_to 'Back', gossips_path %>
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProjectRaf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.2.8.min.css"/>

  </head>

  <body>
    <%= yield %>
  </body>
</html>